# Generated by Django 4.0.4 on 2022-05-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='uuid',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
