# Generated by Django 4.0.4 on 2022-05-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_urls_uuid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls',
            new_name='Url',
        ),
    ]
